app = "tracker-ibh-lq"
primary_region = "cdg"

[env]
  PORT = "8080"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[[http_service.checks]]
  grace_period = "60s"
  interval = "15s"
  timeout = "5s"
  method = "GET"
  path = "/"

[mounts]
  source = "tracker_data"
  destination = "/app/data"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
  count = 1
